language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - composer self-update
  - cd ..

  - git clone --depth 1 --branch 8.0.x https://git.drupal.org/project/drupal.git
  - git clone --depth 1 --branch 8.x-1.x https://git.drupal.org/project/composer_manager.git
  - git clone --depth 1 --branch 8.x-1.x https://git.drupal.org/project/flysystem.git

  - mv composer_manager drupal/modules/composer_manager
  - mv flysystem drupal/modules/flysystem
  - mv drupal_flysystem_s3 drupal/modules/flysystem_s3

  - cd drupal

  - php modules/composer_manager/scripts/init.php
  - composer drupal-rebuild
  - composer update --lock --prefer-source

script:
  - cd modules/flysystem_s3
  - ../../vendor/bin/phpunit

notifications:
  email: false
